# Generated by Django 4.1.7 on 2023-03-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('uploader_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gif_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('gifs', models.ManyToManyField(related_name='category', to='gif.gif')),
            ],
        ),
    ]
